on: pull_request
name: Add label to PR
jobs:
  triage:
    name: Pull Request Labeler
    runs-on: ubuntu-latest
    steps:
      - name: Pull Request Labeler
        uses: actions/labeler@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
